# Generated by Django 2.1.1 on 2018-09-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='dropbox_api_key',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='uid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
