# Generated by Django 2.1.1 on 2018-09-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20180917_0458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uid',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='token_type',
        ),
    ]
